<template>
	<main-layout>

        <!-- Main -->
        <div id="main">
            <!-- One -->
            <section id="one">
                <div class="inner">
                    <header class="major">
                        <h2>What exactly does the Autodesk Forge API do?</h2>
                    </header>
                    <p>The Autodesk Forge Viewer enables web developers to very easily display 3D (and 2D) models in a
                        WebGL-enabled browser or smartphone app. If you've got a model you've created using some kind of
                        design software, then you can probably display it using this technology.</p>
                    <p>The Data Management API provides a unified and consistent way to access data across BIM 360 Team,
                        Fusion Team (formerly known as A360 Team), A360 Personal, and the Object Storage Service.</p>
                    <p>The Model Derivative API enables users to represent and share their designs in different formats,
                        as well as to extract valuable metadata.</p>
                    <p>Formerly known as the “AutoCAD I/O API”, the Design Automation API provides the ability to run
                        scripts on your design files, leveraging the scale of the Forge Platform to automate repetitive
                        tasks.<br />
                        At present, the API provides the ability to run scripts on AutoCAD DWG files, with plans in the
                        works to expand to file types generated by other design software.</p>
                    <ul class="actions">
                        <li><a href="http://viewer-rocks.autodesk.io/" target="demo" class="button next scrolly">See live example here</a></li>
                    </ul>

                    <p>Listen Jim Quanci, Sr. Director, talking about Forge being a platform for you to build the
                        future of making things.</p>
                    <ul class="actions">
                        <li><a href="http://autode.sk/2fS8t7O" target="demo" class="button next scrolly">Watch video</a></li>
                    </ul>

                </div>
            </section>

            <!-- Two -->
            <section id="two" class="spotlights">
                <section id="viewer-api">
                    <a href="https://forge-rcdb.autodesk.io/configurator?id=57f3739777c879f48ad54a44" class="image">
                        <img src="./WhatIsForge/viewer.jpg" alt="" data-position="center center" />
                    </a>
                    <div class="content">
                        <div class="inner">
                            <header class="major">
                                <h3>View 3D models directly in your browser</h3>
                            </header>
                            <p>The Viewer allows you to embed, interact with, and retrieve meta data about design files
                                in over 50 formats right in your browser, without having to install extra software.</p>
                            <p>The API a (client-side) WEBGL/JavaScript API based on Three.js</p>
                            <ul class="actions">
                                <li><a href="https://forge-rcdb.autodesk.io/configurator?id=57f3739777c879f48ad54a44" target="demo" class="button next scrolly">Try it live</a></li>
                                <li><a href="https://github.com/Autodesk-Forge/forge-rcdb.nodejs" target="github" class="button next scrolly">Open on GitHub</a></li>
                            </ul>
                        </div>
                    </div>
                </section>
                <section id="data-management">
                    <a href="https://forgedmboxintegration.herokuapp.com/" class="image">
                        <img src="./WhatIsForge/dm.jpg" alt="" data-position="top center" />
                    </a>
                    <div class="content">
                        <div class="inner">
                            <header class="major">
                                <h3>Centrally manage data</h3>
                            </header>
                            <p>The Data Management API allows you to access your data across A360, Fusion, and the
                                Object Storage Service.</p>
                            <p>The API a (server-side) REST API</p>
                            <ul class="actions">
                                <li><a href="https://forgedmboxintegration.herokuapp.com/" target="demo" class="button next scrolly">Try it live</a></li>
                                <li><a href="https://github.com/Autodesk-Forge/data.management-nodejs-integration.box" target="github" class="button next scrolly">Open on GitHub</a></li>
                            </ul>
                        </div>
                    </div>
                </section>
                <section id="model-derivative">
                    <a href="https://dm.autodesk.io/" class="image">
                        <img src="./WhatIsForge/modelderivative.png" alt="" data-position="25% 25%" />
                    </a>
                    <div class="content">
                        <div class="inner">
                            <header class="major">
                                <h3>Convert your design files to formats that unlock <br />their potential</h3>
                            </header>
                            <p>Use the Model Derivative API to prepare files for the Viewer, extract geometries,
                                retrieve metadata, and more, from over 60+ different industry-standard formats.</p>
                            <p>The API a (server-side) REST API</p>
                            <ul class="actions">
                                <li><a href="https://dm.autodesk.io/" target="demo" class="button next scrolly">Try it live</a></li>
                                <li><a href="https://github.com/Autodesk-Forge/forge-boilers.nodejs/tree/project5" target="github" class="button next scrolly">Open on GitHub</a></li>
                            </ul>
                        </div>
                    </div>
                </section>
                <section id="design-automation">
                    <a href="http://createmybureau.azurewebsites.net/" class="image">
                        <img src="./WhatIsForge/designautomation.png" alt="" data-position="25% 25%" />
                    </a>
                    <div class="content">
                        <div class="inner">
                            <header class="major">
                                <h3>Automate at scale</h3>
                            </header>
                            <p>Leverage the scale of Autodesk's cloud to run automation scripts on your design files.</p>
                            <p>The API a (server-side) REST API</p>
                            <ul class="actions">
                                <li><a href="http://createmybureau.azurewebsites.net/" target="demo" class="button next scrolly">Try it live</a></li>
                                <li><a href="https://github.com/Autodesk-Forge/design.automation-asp.net-cabinet-sample" target="github" class="button next scrolly">Open on GitHub</a></li>
                            </ul>
                        </div>
                    </div>
                </section>
            </section>

        </div>

	</main-layout>
</template>

<script>
	import MainLayout from '../layouts/main.vue' ;

	export default {
		data: function () {
			var navigationMenu =require ('../data/navigation') ;
            for ( var i =0 ; i < navigationMenu.length ; i++ ) {
                if ( navigationMenu [i].image )
                    navigationMenu [i].image =require ('' + navigationMenu [i].image) ;
            }
			return ({
				title: 'What is Forge?',
				description: 'FORGE is a set of web service APIs* that power the future of making things.',
				menu: navigationMenu
			}) ;
		},
		components: {
			MainLayout
		}
	}
</script>

<style>
#banner.WhatIsForge {
    background-image: url(./WhatIsForge/WhatIsForge2.jpg);
}
</style>
